language: node_js
node_js:
- '4.6'
after_success: "./node_modules/.bin/codecov"
deploy:
  provider: npm
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: parse-server-modules/parse-server-push-adapter
